### ISSUE TITLE
could packages store preferred links?

### ISSUE THREAD

**Issue by maelle** [r-lib/downlit#17]
Very niche issue :-)

distill has no pkgdown website which makes sense. Therefore downlit links functions to rdrr.io. It seems suboptimal compared to landing on distill distill website.

It made me think that it might be nice if packages could have some sort of YAML with function name & URL. It might be generated by roxygen2 using some tag, and would be in inst/ therefore installed.

This way

* packages could use something else than a pkgdown website;

* if I prefer folks to read a vignette rather than the man page, I can use that URL.

**Comment by hadley** [comment]
To receive reference and article links, a package has to provide a `/pkgdown.yml` like this:

```yaml
pandoc: 2.9.2.1
pkgdown: 1.4.1.9000
pkgdown_sha: ~
articles:
  extending-ggplot2: extending-ggplot2.html
  ggplot2-in-packages: ggplot2-in-packages.html
  ggplot2-specs: ggplot2-specs.html
  profiling: profiling.html
last_built: 2020-05-13T19:00Z
urls:
  reference: https://ggplot2.tidyverse.org/reference
  article: https://ggplot2.tidyverse.org/articles
```

(from <https://ggplot2.tidyverse.org/pkgdown.yml>)

I think the easiest approach would be for distill to just create this itself (I think only `articles` and `urls` are needed)

But the distill website doesn't contain reference pages or articles, so I'm not sure what you're thinking here?
